### ISSUE TITLE
Optional parameter to decide whether to include hidden categories

### ISSUE THREAD

**Issue by djr-jsr** [abinashmeher999/pymediawiki#15]
While getting the categories for a wiki page, we can provide whether we need hidden categories or not as mentioned [here](https://www.mediawiki.org/wiki/API:Categories). This needs to be implemented in the existing code [wiki_cat.py#L14](https://github.com/abinashmeher999/wikipedia-category/blob/master/wiki_cat.py#L14). This should be sent as parameter to the `get_cat` function. For example,
```python
def get_cat(self, pageid=None, include_hidden=False)
```

**Comment by abinashmeher999** [comment]
Fixed in #19
