### ISSUE TITLE
Specify User-Agent header in all requests.

### ISSUE THREAD

**Issue by abinashmeher999** [abinashmeher999/pymediawiki#30]
As mentioned in the [MediaWiki API:Etiquette](https://www.mediawiki.org/wiki/API:Etiquette#User-Agent_header).

**Comment by abhigyank** [comment]
In the user-agent, User-Agent: Wikipedia- Category and potential website: https://github.com/abinashmeher999/wikipedia-category enough?

**Comment by abinashmeher999** [comment]
Yes, that should be enough. Send a PR and we can modify then.

**Comment by abinashmeher999** [comment]
Closed in favor of #33
