### ISSUE TITLE
Set up a virtual environment

### ISSUE THREAD

**Issue by abinashmeher999** [abinashmeher999/pymediawiki#4]
An isolated environment to which developers can switch and then start contributing. I would prefer Python 3 environment. This might also require minor refactoring of the code too.

**Comment by ayuhsya** [comment]
I'll start with this, this seems easy. :|

**Comment by abinashmeher999** [comment]
Great! Mention me if you run into any issues.

**Comment by ayuhsya** [comment]
@abinashmeher999 I have made the environment. Just to be sure that I did that correctly, can you tell me how does one commit a virtual environment?

Also, what next?

**Comment by abinashmeher999** [comment]
This is the fun part. You can't commit all of the virtual environment. So it would be great if you could write a script(bash script would do) that creates the virtual environment and then prints the instructions to change into it. 

Also you will need to freeze dependent packages into requirements.txt using `pip freeze`. Does that clarify?

**Comment by ayuhsya** [comment]
Yes I've already created the requirements.txt file. Actually, that was the only new addition to the project after creating virtual environment as all others are in .gitignore.
Also, by bash script I assume you mean a MakeFile, so I'll create the same.

**Comment by abinashmeher999** [comment]
No not a makefile. A simple `.sh` file would do, with all the commands that you executed to create it. Also test the Python 3 environment once with the sample code.

**Comment by abinashmeher999** [comment]
@ayuhsya  I see that you have committed the changes on the master branch itself. It is a bad practice to do so. Say you made all your changes to the master branch, you send the PR and let's assume didn't get merged because of some issues. Now you want to work on top of the latest master. Where do you pull that branch to? I hope you understand.

**Comment by harshcrop** [comment]
@abinashmeher999 can I setup virtual environment  in python 2.7 I am very much familiar with this.

**Comment by abinashmeher999** [comment]
@harshcrop We will be using Python 3 in the future because since we are dealing with wikipedia here and there will lots of unicode characters. And handling unicode is lot less painful in Python 3. Besides making a virtualenv for Python 3 is not very different from how you would do that for Python 2.7.

@ayuhsya Has already completed doing it. It would be pointless to the same thing again. Pull @ayuhsya's commits from his master into a new branch and see if you can complete the PR.

**Comment by harshcrop** [comment]
@abinashmeher999 okay make new branch again can check his repo

**Comment by abinashmeher999** [comment]
Sorry didn't get you.

**Comment by harshcrop** [comment]
@abinashmeher999 I am asking that what I have to do now if this task is completed so, can I set up virtual environment for me in my repo and push into my branch and start working on new issue. That what I am asking you??

**Comment by abinashmeher999** [comment]
Yeah you can go ahead. Try #3

**Comment by harshcrop** [comment]
okay doing it

**Comment by ayuhsya** [comment]
@abinashmeher999 Yes I know that we don't work on the master branch. But this task wasn't that major so I didn't bother creating a new branch. :neutral_face:

**Comment by abinashmeher999** [comment]
@ayuhsya You will realise that even a small task doesn't justify working on the master once you are on your second PR(not first) to this repo. Because the work needed then just to clean up is more than just creating a new branch. It's a small change, so no worries :smile:. Better clean it up before it becomes a headache. 

Maybe you can move those commits to a new branch. You can google it on how to do that. It's not uncommon to commit on your master by mistake.

**Comment by ayuhsya** [comment]
Okay, I'll do things on new branch now. But what do I do to send pull request/what else is left to do in this issue?

**Comment by abinashmeher999** [comment]
@ayuhsya Have a look at [this](http://stackoverflow.com/questions/1628563/move-the-most-recent-commits-to-a-new-branch-with-git).

**Comment by abinashmeher999** [comment]
Addressed in #11.
